MapRoulette right click menu
facebook/Rapid pull request #1638
Opened 2024-12-05 23:28 UTC by tannerwuster

**Right click** on the MapRoulette icon and have a small menu pop up to choose one of the four options.
<img width="290" alt="Screenshot 2024-12-05 at 16 25 04" src="https://github.com/user-attachments/assets/08db64e0-e41e-43a9-976f-dbab6e4ccfaf">
closes #1430

2024-12-09 15:03 UTC, bhousel requested changes
Wow this is pretty impressive how quickly you built it!

I think it would be ideally better to use the existing edit menu to show things in different modes - I think somebody had also asked for the Rapid accept/ignore commands to go there too.  

But this is immediately useful and I don't want to hold it up to wait for the Edit Menu to be rewritten, something I can do later when I have more time.

I'll do a review with some feedback, looks mostly pretty good 👍

2024-12-13 16:45 UTC, Bonkles commented on modules/modes/SelectMode.js
> +      uiMapRouletteMenu(context).error(datum);
```suggestion
      let uiSystem = this.context.systems.ui;
      uiSystem.MapRouletteMenu.error(datum);
```

2024-12-13 16:47 UTC, Bonkles commented on modules/modes/SelectMode.js
> +      uiMapRouletteMenu(context).error(datum);
You've already instantiated a new uiMapRouletteMenu object and attached it to the UiSystem via the `MapRouletteMenu` variable- this call completely re-creates the object, so selectMode and UiSystem aren't able to sync up. 

With this change, you should see the _qaItem variable be defined as you take a spin through the body of the menu rendering code.

2024-12-16 21:27 UTC, bhousel approved these changes
Tested this in staging (at least, the best I could with OSM being read-only), and it seems fine.

2024-12-16 21:27 UTC, merged