cursor handling transferred from Rapid V1 to V2
facebook/Rapid pull request #826
Opened 2023-02-27 17:32 UTC by tannerwuster

### Rapid V1 Cursor Handling add to Rapid V2
**This includes the following hover effects:**
- Lasso tool 
- Drawing a connect line 
- Connecting a vertex 
- Select Add
- Select Area 
- Select Line 
- Select Mapillary 
- Select Point 
- Select Remove
- Select Split 
- Select Vertex
_I believe this still needs another iteration that uses the Pixi textures to load the images_
closes #777

2023-03-01 16:28 UTC, Bonkles requested changes
This is a pretty gnarly problem with lots of use cases! Though, I am impressed you've gotten this far with no help. Solid work! You should be very happy. 


A few things here & there, see my inline comments. Some are general code structure/suggestions, some are actual issues i saw in the behavior. 

We will need to take another look at the cursor transitions as you click on a thing, then hover on that thing, then hover off that thing. It doesn't look like the cursor transitions are quite correct in all cases.

2023-03-01 16:28 UTC, Bonkles commented on modules/modes/ModeBrowse.js
> +    if (geom && geom === 'vertex') {
In general, when decision making in an if/else, try to limit things to a single assignment statement at the end (if possible). 

```
let cursorPath;
if (vertex) {
cursorPath = 'url(/img/cursor/cursor-select-vertex.png), auto';
} 
/* ... other clauses cut for brevity  ... */ 
else {
    cursorPath = 'url(/img/cursor/cursor-grab.png),auto';
}

document.body.style.cursor = cursorPath
}

```

2023-03-01 16:28 UTC, Bonkles commented on modules/modes/ModeBrowse.js
> +      document.body.style.cursor = 'url(/img/cursor/cursor-grab.png),auto';
But in this particular case, we can shorten the code to be even more brief: 

```
if (geom && (geom === 'line' || geom === 'area' || geom === 'point'))  {
 document.body.style.cursor = `url(/img/cursor/cursor-select-${geom}.png),auto`;
 }  else {
 document.body.style.cursor = 'url(/img/cursor/cursor-grab.png),auto';
 }
```

2023-03-01 16:28 UTC, Bonkles commented on modules/modes/ModeDrawArea.js
> +      document.body.style.cursor = 'url(/img/cursor/cursor-draw-connect-vertex.png),auto';
I built and ran this branch, and I noticed that the draw cursors are indeed showing up but they're not offset correctly. All the crosshair-style cursors (the ones that begin with 'cursor-draw') will need to be centered directly on the mouse coordinate, unlike the pointer-type that need to be drawn underneath/to the right.

2023-06-21 18:49 UTC, bhousel commented
Going to close this, the code has changed a bunch so it's gone stale.

2023-06-21 18:49 UTC, closed without merging